<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CuratorSeeder extends Seeder
{
    public function run(): void
    {
        $curators = [
            ['Amanov Mexriddin Oromiddinovich', 'amanov.m@tisu.uz'],
            ['Ishmuratov Baxodir Xusanovich', 'ishmuratov.b@tisu.uz'],
            ['Shukurov Sherzod Xolmo`min o`g`li', 'shukurov.s@tisu.uz'],
            ['Uzmanov Ixtiyor Ibragim o\'g\'li', 'uzmanov.i@tisu.uz'],
            ['Abdurahmanova Feruza Fahriddin qizi', 'abdurahmanova.f@tisu.uz'],
            ['Saparov Ismat Chorshanbiyevich', 'saparov.i@tisu.uz'],
            ['Jo\'rayeva Safargul Nurullo qizi', 'jorayeva.s@tisu.uz'],
            ['To\'qsonov Xurshid Egamberdiyevich', 'toqsonov.x@tisu.uz'],
            ['Mamadjanova Tuygʻunoy Axmadjanovna', 'mamadjanova.t@tisu.uz'],
            ['Yarmatov Sharofiddin Choriyevich', 'yarmatov.s@tisu.uz'],
            ['Choriyeva Muattar Sharof qizi', 'choriyeva.m@tisu.uz'],
            ['Oltiboyeva Feruza Ulug\'bek qizi', 'oltiboyeva.f@tisu.uz'],
            ['Boboxonov Muxammadaziz Shavkatovich', 'boboxonov.m@tisu.uz'],
            ['Murodova Ra\'no Anvarovna', 'murodova.r@tisu.uz'],
            ['Eshniyozov Asadbek Abdinazar o\'g\'li', 'eshniyozov.a@tisu.uz'],
            ['Abdurahimov Sarvar Nasrilloyevich', 'abdurahimov.s@tisu.uz'],
            ['Xurramov Ruslan Erkin o\'g\'li', 'xurramov.r@tisu.uz'],
            ['Jo\'rayev Husan Atamuradovich', 'jorayev.h@tisu.uz'],
            ['Odilov Umid Abduxalimovich', 'odilov.u@tisu.uz'],
            ['Mamatrayimov Shahzod Qo\'shshoq o\'g\'li', 'mamatrayimov.s@tisu.uz'],
            ['Qodirov Xasan Do\'stqobilovich', 'qodirov.x@tisu.uz'],
            ['Do\'smuxamedova Nozima Xamidulla qizi', 'dosmuxamedova.n@tisu.uz'],
            ['Abdusamatov Mamayusuf Kulmonovich', 'abdusamatov.m@tisu.uz'],
            ['Xudoyorova Zuxra Yuldoshevna', 'xudoyorova.z@tisu.uz'],
            ['Yusupov Gulboy Amirovich', 'yusupov.g@tisu.uz'],
            ['Absamatov Asqar Ergashevich', 'absamatov.a@tisu.uz'],
            ['Solixova Xumora Xasan qizi', 'solixova.x@tisu.uz'],
            ['Avazova Elsevar Erkinovna', 'avazova.e@tisu.uz'],
            ['Nomozova Rayhona Rustamovna', 'nomozova.r@tisu.uz'],
            ['Kenjayev Kattako\'l Nurmatovich', 'kenjayev.k@tisu.uz'],
            ['Sottorov Abduvali Umirqulovich', 'sottorov.a@tisu.uz'],
            ['Ramazanov Xusniddin Saidaxmadovich', 'ramazanov.x@tisu.uz'],
            ['Panjiyeva Nazokat Normaxmatovna', 'panjiyeva.n@tisu.uz'],
            ['Raximov Furqat Rashid o\'g\'li', 'raximov.f@tisu.uz'],
            ['Xoliyarov Erkin Chorshanbiyevich', 'xoliyarov.e@tisu.uz'],
            ['Odinayev Abduvohid Shuxrat o\'g\'li', 'odinayev.a@tisu.uz'],
            ['Abrayeva Sevara Toshtemirovna', 'abrayeva.s@tisu.uz'],
            ['Buriyev Javoxir Nosir o\'g\'li', 'buriyev.j@tisu.uz'],
            ['Jumayev Azamat Qurbonali o\'g\'li', 'jumayev.a@tisu.uz'],
            ['Qosimov Odilbek Yunusovich', 'qosimov.o@tisu.uz'],
            ['Erdonov Bekmurod Xolboy o\'g\'li', 'erdonov.b@tisu.uz'],
            ['Abrayev Baxrom Xonto\'rayevich', 'abrayev.b@tisu.uz'],
            ['Abduraimova Nigora Abdugapparovna', 'abduraimova.n@tisu.uz'],
            ['Ergashev Akmal Abdurasul o\'g\'li', 'ergashev.a@tisu.uz'],
            ['Erdanayev Bunyod Abdumalikovich', 'erdanayev.b@tisu.uz'],
            ['Xoshbaqov Baxodir Abdulazizovich', 'xoshbaqov.b@tisu.uz'],
            ['Pardayev Anvar Yusupovich', 'pardayev.a@tisu.uz'],
            ['Xolmatova Asila Menglimurod qizi', 'xolmatova.a@tisu.uz'],
            ['Muminova Mavjuda Sharipovna', 'muminova.m@tisu.uz'],
            ['Xurramov Ramazon Allayor o\'g\'li', 'xurramov.r2@tisu.uz'],
            ['Turayev Baxtiyor Ergashevich', 'turayev.b@tisu.uz'],
            ['Namozov Gafur Shokulovich', 'namozov.g@tisu.uz'],
            ['Toyirov Akbar Xasanovich', 'toyirov.a@tisu.uz'],
            ['Xurramov Nosir Xamidovich', 'xurramov.n@tisu.uz'],
            ['Bobomurodov Ulug\'bek Erkinovich', 'bobomurodov.u@tisu.uz'],
            ['Xaydarova Shoxista Davronovna', 'xaydarova.s@tisu.uz'],
            ['Rashidova Xadicha Tursunalievna', 'rashidova.x@tisu.uz'],
            ['Nuriddinov Elyorjon Baxtiyor oʻgʻli', 'nuriddinov.e@tisu.uz'],
            ['Muzropova Shaxnoza Saydullayevna', 'muzropova.s@tisu.uz'],
            ['Madjitova Maftuna Kamiljon', 'madjitova.m@tisu.uz'],
            ['Shodiev Akbar Ashurovich', 'shodiev.a@tisu.uz'],
            ['Xakimov Zafar Ibragimovich', 'xakimov.z@tisu.uz'],
            ['Eshqulova Nasiba Normo\'minovna', 'eshqulova.n@tisu.uz'],
            ['To\'xtaeva Nazokat Rustamovna', 'toxtaeva.n@tisu.uz'],
            ['To\'raev Dilmurod Shokir o\'g\'li', 'toraev.d@tisu.uz'],
            ['Ernazarov Mirzohid Yuldash o\'g\'li', 'ernazarov.m@tisu.uz'],
            ['To\'rayev Ziyodulla Norsoatovich', 'torayev.z@tisu.uz'],
            ['Pardayev Lochinbek Farxod o\'g\'li', 'pardayev.l@tisu.uz'],
            ['Ismatov Sharofiddin Asadullayevich', 'ismatov.s@tisu.uz'],
            ['Ziyodullayev Sodiqjon Mamadaliyevich', 'ziyodullayev.s@tisu.uz'],
            ['Begaliyev Azizjon Olimnazarovich', 'begaliyev.a@tisu.uz'],
            ['Salohiddinova Navro\'za Murodulla qizi', 'salohiddinova.n@tisu.uz'],
            ['Tojiyev Husniddin Baxtiyorovich', 'tojiyev.h@tisu.uz'],
            ['Toshpulatova Niyoxon Shavkatjon qizi', 'toshpulatova.n@tisu.uz'],
            ['Djumayeva Dildora Isroilovna', 'djumayeva.d@tisu.uz'],
            ['Saidmurodov Asliddin Dilmurod o\'g\'li', 'saidmurodov.a@tisu.uz'],
            ['Bakirov Juma Ashurovich', 'bakirov.j@tisu.uz'],
            ['Ro\'ziyeva Mashhura Abdumo\'minovna', 'roziyeva.m@tisu.uz'],
            ['Jumayev Ilhom Hamroyevich', 'jumayev.i@tisu.uz'],
            ['Turayeva Gulnoza Ergashevna', 'turayeva.g@tisu.uz'],
            ['Badalov Dilmurod Abdixalilovich', 'badalov.d@tisu.uz'],
            ['Zokirov Javohir G\'aybullayevich', 'zokirov.j@tisu.uz'],
            ['Ibodullayeva Dinara Bahramjanovna', 'ibodullayeva.d@tisu.uz'],
            ['Norqobilova Rayxon Davlatovna', 'norqobilova.r@tisu.uz'],
            ['Kayumova Shaxnoza Kobiljonovna', 'kayumova.s@tisu.uz'],
            ['Erdanova Muxlisa Hoshim qizi', 'erdanova.m@tisu.uz'],
            ['Yadigarova Sitora Bahromovna', 'yadigarova.s@tisu.uz'],
            ['Ochilova Aziza Alisher qizi', 'ochilova.a@tisu.uz'],
            ['Omonova Nilufar Omon qizi', 'omonova.n@tisu.uz'],
            ['Oltiboyeva Kamola Sharofjon qizi', 'oltiboyeva.k@tisu.uz'],
            ['Toshova Shaxnoza Tojinorovna', 'toshova.s@tisu.uz'],
            ['Qosimov Botir Saidvali o\'g\'li', 'qosimov.b@tisu.uz'],
            ['Pardayev Alisher Ochilovich', 'pardayev.a2@tisu.uz'],
            ['Toshov Kamoliddin Tojinorovich', 'toshov.k@tisu.uz'],
            ['Tursunov Anvar Saypullayevich', 'tursunov.a@tisu.uz'],
            ['Abdunabiyev Hikmatulla Exsonovich', 'abdunabiyev.h@tisu.uz'],
            ['Tursunov Uktam Sayfullayevich', 'tursunov.u@tisu.uz'],
            ['Mamarajabov G\'ayrat Abdulxakimovich', 'mamarajabov.g@tisu.uz'],
            ['Abduraxmonov Azamat Ostanaqulovich', 'abduraxmonov.a@tisu.uz'],
            ['Karimov Akbar Ortiqovich', 'karimov.a@tisu.uz'],
            ['Raimov Lazizjon Alisherovich', 'raimov.l@tisu.uz'],
            ['Qosimov Abdusattor Choriyevich', 'qosimov.a@tisu.uz'],
            ['Raupova Navbahor Bahriddinovna', 'raupova.n@tisu.uz'],
            ['Mukumova Dilafruz Ziyodullayevna', 'mukumova.d@tisu.uz'],
            ['Rahmonov Botir Abdurasulovich', 'rahmonov.b@tisu.uz'],
            ['Jo\'rayeva Gavhar Eshqobilovna', 'jorayeva.g@tisu.uz'],
            ['Xayrullayeva Larisa Erkin qizi', 'xayrullayeva.l@tisu.uz'],
            ['Xabibullayeva Shoira Shukrullayevan', 'xabibullayeva.s@tisu.uz'],
            ['Qoraqulov Azizbek Amanqulovich', 'qoraqulov.a@tisu.uz'],
            ['Qurbonova Shahlo Salomovna', 'qurbonova.s@tisu.uz'],
            ['Tangirov Ro\'ziboy Xudoyshukurovich', 'tangirov.r@tisu.uz'],
            ['Chorshanbiyev Anvar Allaberdi o\'g\'li', 'chorshanbiyev.a@tisu.uz'],
            ['Ismoilova Sabina Erkin qizi', 'ismoilova.s@tisu.uz'],
            ['Rahmonqulova Feruza Umidullayevna', 'rahmonqulova.f@tisu.uz'],
            ['Muxammadiyeva Dinora Tursunpulatovna', 'muxammadiyeva.d@tisu.uz'],
            ['Xayitmurodova Gulnoza To\'ra qizi', 'xayitmurodova.g@tisu.uz'],
            ['Xaitov Abduqosim Abdulakim o\'g\'li', 'xaitov.a@tisu.uz'],
            ['Badalov Kamoliddin Rahmat o\'g\'li', 'badalov.k@tisu.uz'],
            ['Misirova Nozanin Nurullo qizi', 'misirova.n@tisu.uz'],
            ['Mingto\'rayeva Umida Anvar qizi', 'mingtorayeva.u@tisu.uz'],
            ['Mengboyev Azizbek Alijon o\'g\'li', 'mengboyev.a@tisu.uz'],
            ['Narmuratov Zayniddin Rajabovich', 'narmuratov.z@tisu.uz'],
            ['Choriyev Ulug\'bek Normeyliyevich', 'choriyev.u@tisu.uz'],
            ['Mingnarova Maftuna Toshboy qizi', 'mingnarova.m@tisu.uz'],
            ['Shodiyeva Nodira Normamatovna', 'shodiyeva.n@tisu.uz'],
            ['Xurramova Dilso\'z Baxtiyorovna', 'xurramova.d@tisu.uz'],
            ['Shonazarova Gulnoza Shuxrat qizi', 'shonazarova.g@tisu.uz'],
            ['Xaydarova Mahliyo Xabibullayevna', 'xaydarova.m@tisu.uz'],
            ['Abdunazarov O`ktam Qushoqvich', 'abdunazarov.o@tisu.uz'],
            ['Toshboyeva Ug\'ilshod Abduvohidovna', 'toshboyeva.u@tisu.uz'],
            ['Mengliqulova Manzura Abdullayevna', 'mengliqulova.m@tisu.uz'],
            ['Azizjonova Asilabonu Alisher qizi', 'azizjonova.a@tisu.uz'],
            ['Masadikova Xilola Bahromovna', 'masadikova.x@tisu.uz'],
            ['Rahimova Shaxzoda Do\'stmurodovna', 'rahimova.s@tisu.uz'],
            ['Norqobilova Nigora Uralovna', 'norqobilova.n@tisu.uz'],
            ['Qurbonova Nazira Nizomiddinova', 'qurbonova.n@tisu.uz'],
            ['Xonova Dilrabo Baratovna', 'xonova.d@tisu.uz'],
            ['Hudoyorova Gulnora Nuriddinovna', 'hudoyorova.g@tisu.uz'],
            ['Kamalov Umid Achilovich', 'kamalov.u@tisu.uz'],
            ['Mahmadiyeva Gulchehra Said-Abdullayevna', 'mahmadiyeva.g@tisu.uz'],
            ['Alimardanova Ra\'no Narbayevna', 'alimardanova.r@tisu.uz'],
            ['Jo\'rayev Atham Qoraqulovich', 'jorayev.a@tisu.uz'],
            ['Avliyaqulov Tolib Xolmurodovich', 'avliyaqulov.t@tisu.uz'],
            ['Almardanov Jo\'rabek Babanazarovich', 'almardanov.j@tisu.uz'],
            ['Xo\'jamqulova Iroda Faxriddin qizi', 'xojamqulova.i@tisu.uz'],
            ['Qarshiyeva Iroda Baxtiyorovna', 'qarshiyeva.i@tisu.uz'],
            ['Eshqorayev Ulug\'bek Choriyevich', 'eshqorayev.u@tisu.uz'],
            ['Bekmirzayev Shavkat Olim o\'g\'li', 'bekmirzayev.s@tisu.uz'],
            ['Ibragimov Aziz Ilhomovich', 'ibragimov.a@tisu.uz'],
            ['Usmonov Mansur Qurbonmurotovich', 'usmonov.m@tisu.uz'],
            ['Babayev Anvar Axmedovich', 'babayev.a@tisu.uz'],
            ['Salomov G\'ulom Yuldoshevich', 'salomov.g@tisu.uz'],
            ['Hayitova Feruza Abdullayevna', 'hayitova.f@tisu.uz'],
            ['Bazarov Sobirjon Bektoshevich', 'bazarov.s@tisu.uz'],
            ['Abdinabiyev Xikmatulla Ehsonovich', 'abdinabiyev.x@tisu.uz'],
            ['Yuldashev Elyor Abdusalom o\'g\'li', 'yuldashev.e@tisu.uz'],
            ['Shoyimova Komila O`ral qizi', 'shoyimova.k@tisu.uz'],
            ['Mingboyev Otabek Alijon o\'g\'li', 'mingboyev.o@tisu.uz'],
            ['Bo`riyeva Muxayyo Shavkatovna', 'boriyeva.m@tisu.uz'],
            ['Toshpo`latov Akmal Xolmirzayevich', 'toshpolatov.a@tisu.uz'],
            ['Bo`riyeva Shaxnoza G`ofur qizi', 'boriyeva.s@tisu.uz'],
            ['Bo\'riyev Sardor Bobur o\'g\'li', 'boriyev.s@tisu.uz'],
            ['Qalandarov Qalandar Abduraximovich', 'qalandarov.q@tisu.uz'],
            ['Mengnarov Abdulla Xolmo\'min o\'g\'li', 'mengnarov.a@tisu.uz'],
            ['Nazarov Otabek Muzrobobich', 'nazarov.o@tisu.uz'],
            ['Abdurahmonov Akmal Yuldoshovich', 'abdurahmonov.a@tisu.uz'],
            ['Fayzullayeva Mavluda Xamzayevna', 'fayzullayeva.m@tisu.uz'],
            ['Boysoatov Muzaffar Bo`ri o`g`li', 'boysoatov.m@tisu.uz'],
            ['Ahmedov Erkin Qurbonovich', 'ahmedov.e@tisu.uz'],
            ['Norqulova Shaxnoza To`lqinovna', 'norqulova.s@tisu.uz'],
            ['Xolmurotova Shohista Mirzaliyevna', 'xolmurotova.s@tisu.uz'],
            ['Aminova Dilnoza Orifjonovna', 'aminova.d@tisu.uz'],
            ['Jumayeva Shohida Choriyevna', 'jumayeva.s@tisu.uz'],
            ['Nematullayev Nodir Muzaffar o`g`li', 'nematullayev.n@tisu.uz'],
            ['Allayarova Salomat Panjiyevna', 'allayarova.s@tisu.uz'],
            ['O`ralova Oysuluv Poyonovna', 'oralova.o@tisu.uz'],
            ['Saydullayev Farrux Umidovich', 'saydullayev.f@tisu.uz'],
            ['Berdimurodova Sevara Mahmudovna', 'berdimurodova.s@tisu.uz'],
            ['Sohibova Dilnoza Ergashovna', 'sohibova.d@tisu.uz'],
            ['Qodirova Sarvinoz Ravshan qizi', 'qodirova.s@tisu.uz'],
            ['Ro`zimurodova Shohista Akbar qizi', 'rozimurodova.s@tisu.uz'],
            ['Jabborova Nargiza Islomjonovna', 'jabborova.n@tisu.uz'],
            ['Jumayev Otabek Alisherovich', 'jumayev.o@tisu.uz'],
            ['Sattarova Yelena Anatolyevna', 'sattarova.y@tisu.uz'],
            ['Norbosheva Maqsuda Achilovna', 'norbosheva.m@tisu.uz'],
            ['Boboqulov Chori O`rolovich', 'boboqulov.c@tisu.uz'],
            ['Begimkulov Oltiboy Jo\'raevich', 'begimkulov.o@tisu.uz'],
            ['Mengturayeva Umida Anvar qizi', 'mengturayeva.u@tisu.uz'],
            ['Abdusamatov Alisher Sobirovich', 'abdusamatov.a@tisu.uz'],
            ['Eshboyeva Surayyo Qahramon qizi', 'eshboyeva.s@tisu.uz'],
            ['Babayeva Maxfuza Abduvoitovna', 'babayeva.m@tisu.uz'],
            ['Davlyatova Matluba Xolmo\'minovna', 'davlyatova.m@tisu.uz'],
            ['Jabborov Faxriddin Alisherovich', 'jabborov.f@tisu.uz'],
            ['Mustafaqulova Zarifa Baxodir qizi', 'mustafaqulova.z@tisu.uz'],
            ['Yormatova Faxriddin Jaylovovich', 'yormatova.f@tisu.uz'],
            ['Eshqurbonov Sirojiddin Bozorovich', 'eshqurbonov.s@tisu.uz'],
            ['Qobilov Kamoliddin Eshboltayevich', 'qobilov.k@tisu.uz'],
            ['Bobomurodova Shoira Erkinovna', 'bobomurodova.s@tisu.uz'],
            ['Almardonova Iroda Toshmamatovna', 'almardonova.i@tisu.uz'],
            ['Ergasheva Rayhon O\'tkirovna', 'ergasheva.r@tisu.uz'],
            ['Habibullayeva Shoira Shururullayevna', 'habibullayeva.s@tisu.uz'],
            ['Mengnarov Abdulla Xolmo\'min o\'g\'li', 'mengnarov.a2@tisu.uz'],
            ['Jabbarova Subhida Abdullayevna', 'jabbarova.s@tisu.uz'],
            ['Ismoilov Bobur Tohirovich', 'ismoilov.b@tisu.uz'],
            ['Shonazarova Sevara Rashidovna', 'shonazarova.s@tisu.uz'],
            ['Xurramova Mohidil Baxtiyorovna', 'xurramova.m@tisu.uz'],
            ['Xamrayeva Ra\'no Rajapovna', 'xamrayeva.r@tisu.uz'],
            ['Xolov Olim Chorshamiyevich', 'xolov.o@tisu.uz'],
            ['Jumayeva Gulnora Tursunpo\'latovna', 'jumayeva.g@tisu.uz'],
            ['Almardanov Jo\'rabek Bobonazarovich', 'almardanov.j2@tisu.uz'],
            ['Qarshiyeva Iroda Baxtiyorovna', 'qarshiyeva.i2@tisu.uz'],
            ['Salimov O\'tkirjon Saydullayevich', 'salimov.o@tisu.uz'],
            ['Jo`rayev Atham Qoraqulovich', 'jorayev.a2@tisu.uz'],
            ['Badalov Kamoliddin Rahmat o`g`li', 'badalov.k2@tisu.uz'],
            ['Amirqulova Zebiniso Mustafaqulovna', 'amirqulova.z@tisu.uz'],
            ['Abdinazarov O\'ktam Qushoqovich', 'abdinazarov.o@tisu.uz'],
            ['Salomova Gavhar Abdunazarovna', 'salomova.g@tisu.uz'],
            ['Tursunov Nurullo Narzullayevich', 'tursunov.n@tisu.uz'],
            ['Karimov Abdulaziz Nurullayevich', 'karimov.a2@tisu.uz'],
            ['Allayev Zafar Mengboyevich', 'allayev.z@tisu.uz'],
            ['Madiyeva Madina Yusupovna', 'madiyeva.m@tisu.uz'],
            ['Suleymanov Damir Nazinovich', 'suleymanov.d@tisu.uz'],
            ['Xaitov Abduqosim Abdulakim o`g`li', 'xaitov.a2@tisu.uz'],
            ['Rasulov Abdusamat Abdujabborovich', 'rasulov.a@tisu.uz'],
            ['Buzrukov To\'lqin Omonovich', 'buzrukov.t@tisu.uz'],
            ['Umirqulova Feruza Absamatovna', 'umirqulova.f@tisu.uz'],
            ['Ro\'ziyeva Gulsara Temirqulovna', 'roziyeva.g@tisu.uz'],
            ['Babamuratov Bekzod Ergashevich', 'babamuratov.b@tisu.uz'],
            ['Yarov Umidullo A\'zamovich', 'yarov.u@tisu.uz'],
            ['Tillyayeva Zarina Zafarbekovna', 'tillyayeva.z@tisu.uz'],
            ['Tashpo\'latov To\'lqin Aliyarovich', 'tashpolatov.t@tisu.uz'],
            ['Тo\'rауev Хауrulla Erkin o\'g\'li', 'torauev.x@tisu.uz'],
            ['Annayev Umidjon Faxriddinovich', 'annayev.u@tisu.uz'],
            ['Tog\'ayev Azizbek Aliyor o\'g\'li', 'togayev.a@tisu.uz'],
            ['Meyliyev Zohid Shavkat o\'g\'li', 'meyliyev.z@tisu.uz'],
            ['Saidov Jasur Baxtiyorovich', 'saidov.j@tisu.uz'],
            ['Nurislomova Latofat Fazliddinovna', 'nurislomova.l@tisu.uz'],
            ['Soatova Zarina Akbarovna', 'soatova.z@tisu.uz'],
            ['Qayumova Shaxnoza Jamshidovna', 'qayumova.s@tisu.uz'],
            ['Ko\'chkeldiyeva Shaxnoza Chorshanbiyevna', 'kochkeldiyeva.s@tisu.uz'],
            ['Boyqobilov Soatmurod Shuxratovich', 'boyqobilov.s@tisu.uz'],
            ['Chariyev Muzaffarbek Yudashevich', 'chariyev.m@tisu.uz'],
            ['Boyqulov To\'rabek Temirovich', 'boyqulov.t@tisu.uz'],
            ['Kibriyeva Maxfirat Abduraxmonovna', 'kibriyeva.m@tisu.uz'],
            ['Jo\'rayev Sanjar Ramazonovich', 'jorayev.s@tisu.uz'],
            ['Ko\'charova Ma\'mura Faxriddin qizi', 'kocharova.m@tisu.uz'],
            ['Qurbonova Gulnoza Abduraim qizi', 'qurbonova.g@tisu.uz'],
            ['Hazratqulova Ozoda Abdug\'aniyevna', 'hazratqulova.o@tisu.uz'],
            ['Xamrayev Rashid Ravshan o\'g\'li', 'xamrayev.r@tisu.uz'],
            ['Tojimurodov Mansur Tojimurodovich', 'tojimurodov@tisu.uz'],
            ['Jo\'rayev Zoxidjon Ashurovich', 'jorayev.z@tisu.uz'],
            ['Sultonov Ravshan Komiljonovich', 'sultonov.r@tisu.uz'],
            ['Sultonov Sirojiddin Nuraliyevich', 'sultonov.s@tisu.uz'],
            ['Aslanova Xolida Gafurovna', 'slanova.x@tisu.uz'],
            ['Raimov Shaxboz Qurbonmuratovich', 'raimov.s@tisu.uz'],
            ['Xolmurodov Inoyatullo Ismatulloyevich', 'xolmurodov.i@tisu.uz'],
            ['Axmedov Ulug\'bek Xolbekovich', 'axmedov.u@tisu.uz'],
            ['Babamurodov Alisher Ruzibayevich', 'babamurodov.a@tisu.uz'],
            ['Eshqobilov Ozodbek Abdusodiqovich', 'eshqobilov.o@tisu.uz'],
            ['Kenjayev Yodgor Mamatqulovich', 'enjayev.y@tisu.uz'],
            ['Xudoyqulova Zebo Ravshanovna', 'xudoyqulova.z@tisu.uz'],
            ['Tursunov Quvonchbek Nasim o\'g\'li', 'tursunov.q@tisu.uz'],
            ['Bekmirzayev Eshquvvat Ro\'ziboyevich', 'bekmirzayev.e@tisu.uz'],
            ['Ziyodullayeva Leyla Ibrohimovna', 'ziyodullayeva.l@tisu.uz'],
            ['Bo\'riyev Muhammadali G\'ayrat o\'g\'li', 'boriyev.m@tisu.uz'],
            ['Alimova Zebiniso Farxodjon qizi', 'alimova.z@tisu.uz'],
            ['Po\'latov Muhriddin Qo\'zimuradovich', 'polatov.m@tisu.uz'],
            ['Ergashev Navruzbek Allanazar o\'g\'li', 'ergashev.n@tisu.uz'],
            ['Mamadiyeva Zarifa Norboyeva', 'mamadiyeva.z@tisu.uz'],
            ['Xalbayeva Zarina Kaxramanovna', 'xalbayeva.z@tisu.uz'],
            ['Shermatov Xolbek Faxriddinovich', 'shermatov.x@tisu.uz'],
            ['Chorshanbiyev Chori Xudaymuradov', 'chorshanbiyev.c@tisu.uz'],
            ['Xaitov Akmal Alyarovich', 'xaitov.a3@tisu.uz'],
            ['Saidov Xusniddin Shamsiddin o\'g\'li', 'saidov.x@tisu.uz'],
            ['Husanov Sayidbek Almat o\'g\'li', 'husanov.s@tisu.uz'],
            ['Bo\'riyeva Dilnoza Baxriddinovna', 'boriyeva.d@tisu.uz'],
            ['Ibragimova Gulmira Rashidovna', 'ibragimova.g@tisu.uz'],
            ['Kibriyev Behruz Abdurahmonovich', 'kibriyev.b@tisu.uz'],
            ['Aminqulov Shahrijahon O\'tkir o\'g\'li', 'aminqulov.s@tisu.uz'],
            ['Abdusamiyeva Nargiza Qudratovna', 'abdusamiyeva.n@tisu.uz'],
            ['Choriyev Abubakir Chorshamiyevich', 'choriyev.a@tisu.uz'],
            ['Hayitova Mehrigul Alijon qizi', 'hayitova.m@tisu.uz'],
            ['Pardayev Otabek Anvarovich', 'pardayev.o@tisu.uz'],
            ['Oqboyev Zairullo Bo\'riyevich', 'oqboyev.z@tisu.uz'],
            ['Ro\'ziyev Oybek Avlayevich', 'roziyev.o@tisu.uz'],
            ['Xolboyev Norbek Aliniyozovich', 'xolboyev.n@tisu.uz'],
        ];

        $password = Hash::make('tisu2026');

        foreach ($curators as [$name, $email]) {
            User::create([
                'name' => $name,
                'email' => $email,
                'password' => $password,
                'role' => 'curator',
                'is_active' => true,
            ]);
        }
    }
}
