<?php

namespace Database\Seeders;

use App\Models\Faculty;
use App\Models\Group;
use App\Models\User;
use Illuminate\Database\Seeder;

class GroupSeeder extends Seeder
{
    public function run(): void
    {
        $faculties = Faculty::pluck('id', 'name');
        $curators = User::where('role', 'curator')->pluck('id', 'email');

        // [group_name, faculty_name, curator_email]
        $groups = [
            ['K.IQT-1-25', 'Iqtisodiyot va axborot texnologiyalari', 'amanov.m@tisu.uz'],
            ['K.IQT-2-25', 'Iqtisodiyot va axborot texnologiyalari', 'ishmuratov.b@tisu.uz'],
            ['K.IQT-3-25', 'Iqtisodiyot va axborot texnologiyalari', 'shukurov.s@tisu.uz'],
            ['K.IQT-4-25', 'Iqtisodiyot va axborot texnologiyalari', 'uzmanov.i@tisu.uz'],
            ['K.IQT-5-25', 'Iqtisodiyot va axborot texnologiyalari', 'abdurahmanova.f@tisu.uz'],
            ['K.IQT-6-25', 'Iqtisodiyot va axborot texnologiyalari', 'saparov.i@tisu.uz'],
            ['K.IQT-7-25', 'Iqtisodiyot va axborot texnologiyalari', 'jorayeva.s@tisu.uz'],
            ['K.IQT-8-25', 'Iqtisodiyot va axborot texnologiyalari', 'toqsonov.x@tisu.uz'],
            ['K.IQT-9-25', 'Iqtisodiyot va axborot texnologiyalari', 'mamadjanova.t@tisu.uz'],
            ['K.IQT-10-25', 'Iqtisodiyot va axborot texnologiyalari', 'yarmatov.s@tisu.uz'],
            ['K.IQT-11-25', 'Iqtisodiyot va axborot texnologiyalari', 'choriyeva.m@tisu.uz'],
            ['K.IQT-12-25', 'Iqtisodiyot va axborot texnologiyalari', 'choriyeva.m@tisu.uz'],
            ['K.IQT-13-25', 'Iqtisodiyot va axborot texnologiyalari', 'oltiboyeva.f@tisu.uz'],
            ['K.IQT-14-25', 'Iqtisodiyot va axborot texnologiyalari', 'boboxonov.m@tisu.uz'],
            ['K.IQT-15-25', 'Iqtisodiyot va axborot texnologiyalari', 'murodova.r@tisu.uz'],
            ['K.IQT-16-25', 'Iqtisodiyot va axborot texnologiyalari', 'eshniyozov.a@tisu.uz'],
            ['K.IQT-17-25', 'Iqtisodiyot va axborot texnologiyalari', 'abdurahimov.s@tisu.uz'],
            ['K.IQT-18-25', 'Iqtisodiyot va axborot texnologiyalari', 'xurramov.r@tisu.uz'],
            ['K.MMT-1-25', 'Iqtisodiyot va axborot texnologiyalari', 'jorayev.h@tisu.uz'],
            ['K.MMT-2-25', 'Iqtisodiyot va axborot texnologiyalari', 'odilov.u@tisu.uz'],
            ['K.MMT-3-25', 'Iqtisodiyot va axborot texnologiyalari', 'mamatrayimov.s@tisu.uz'],
            ['K.MMT-4-25', 'Iqtisodiyot va axborot texnologiyalari', 'qodirov.x@tisu.uz'],
            ['K.BX-1-25', 'Iqtisodiyot va axborot texnologiyalari', 'dosmuxamedova.n@tisu.uz'],
            ['K.BX-2-25', 'Iqtisodiyot va axborot texnologiyalari', 'abdusamatov.m@tisu.uz'],
            ['K.BI-1-25', 'Iqtisodiyot va axborot texnologiyalari', 'xudoyorova.z@tisu.uz'],
            ['K.BI-2-25', 'Iqtisodiyot va axborot texnologiyalari', 'yusupov.g@tisu.uz'],
            ['K.BI-3-25', 'Iqtisodiyot va axborot texnologiyalari', 'absamatov.a@tisu.uz'],
            ['K.JIXIM-1-25', 'Iqtisodiyot va axborot texnologiyalari', 'solixova.x@tisu.uz'],
            ['K.JIXIM-2-25', 'Iqtisodiyot va axborot texnologiyalari', 'abdurahmanova.f@tisu.uz'],
            ['K.JIXIM-3-25', 'Iqtisodiyot va axborot texnologiyalari', 'avazova.e@tisu.uz'],
            ['K.TUR-1-25', 'Iqtisodiyot va axborot texnologiyalari', 'nomozova.r@tisu.uz'],
            ['K.S-1-25', 'Iqtisodiyot va axborot texnologiyalari', 'kenjayev.k@tisu.uz'],
            ['K.ATT-1-25', 'Iqtisodiyot va axborot texnologiyalari', 'sottorov.a@tisu.uz'],
            ['K.ATT-2-25', 'Iqtisodiyot va axborot texnologiyalari', 'ramazanov.x@tisu.uz'],
            ['K.ATT-3-25', 'Iqtisodiyot va axborot texnologiyalari', 'panjiyeva.n@tisu.uz'],
            ['K.ATT-4-25', 'Iqtisodiyot va axborot texnologiyalari', 'raximov.f@tisu.uz'],
            ['K.ATT-5-25', 'Iqtisodiyot va axborot texnologiyalari', 'xoliyarov.e@tisu.uz'],
            ['K.ATT-6-25', 'Iqtisodiyot va axborot texnologiyalari', 'odinayev.a@tisu.uz'],
            ['K.ATT-7-25', 'Iqtisodiyot va axborot texnologiyalari', 'abrayeva.s@tisu.uz'],
            ['K.ATT-8-25', 'Iqtisodiyot va axborot texnologiyalari', 'buriyev.j@tisu.uz'],
            ['K.ATT-9-25', 'Iqtisodiyot va axborot texnologiyalari', 'jumayev.a@tisu.uz'],
            ['K.MAT-1-25', 'Iqtisodiyot va axborot texnologiyalari', 'qosimov.o@tisu.uz'],
            ['K.MAT-2-25', 'Iqtisodiyot va axborot texnologiyalari', 'erdonov.b@tisu.uz'],
            ['K.MAT-3-25', 'Iqtisodiyot va axborot texnologiyalari', 'abrayev.b@tisu.uz'],
            ['K.IQT-124', 'Iqtisodiyot va axborot texnologiyalari', 'abduraimova.n@tisu.uz'],
            ['K.IQT-224', 'Iqtisodiyot va axborot texnologiyalari', 'ergashev.a@tisu.uz'],
            ['K.IQT-324', 'Iqtisodiyot va axborot texnologiyalari', 'erdanayev.b@tisu.uz'],
            ['K.IQT-424', 'Iqtisodiyot va axborot texnologiyalari', 'xoshbaqov.b@tisu.uz'],
            ['K.IQT-524', 'Iqtisodiyot va axborot texnologiyalari', 'pardayev.a@tisu.uz'],
            ['K.MMT-1-24.', 'Iqtisodiyot va axborot texnologiyalari', 'xolmatova.a@tisu.uz'],
            ['K.MMT-2-24', 'Iqtisodiyot va axborot texnologiyalari', 'muminova.m@tisu.uz'],
            ['K.BX-1-24', 'Iqtisodiyot va axborot texnologiyalari', 'xurramov.r2@tisu.uz'],
            ['K.BI-1-24', 'Iqtisodiyot va axborot texnologiyalari', 'boboxonov.m@tisu.uz'],
            ['K.JIXIM-1-24', 'Iqtisodiyot va axborot texnologiyalari', 'solixova.x@tisu.uz'],
            ['K.T-1- 24', 'Iqtisodiyot va axborot texnologiyalari', 'turayev.b@tisu.uz'],
            ['K.ATT-1-24', 'Iqtisodiyot va axborot texnologiyalari', 'namozov.g@tisu.uz'],
            ['K.ATT-2-24', 'Iqtisodiyot va axborot texnologiyalari', 'toyirov.a@tisu.uz'],
            ['K.ATT-3-24', 'Iqtisodiyot va axborot texnologiyalari', 'xurramov.n@tisu.uz'],
            ['K.M-1-24', 'Iqtisodiyot va axborot texnologiyalari', 'bobomurodov.u@tisu.uz'],
            ['K.IQT-1-23', 'Iqtisodiyot va axborot texnologiyalari', 'amanov.m@tisu.uz'],
            ['K.IQT-2-23', 'Iqtisodiyot va axborot texnologiyalari', 'xaydarova.s@tisu.uz'],
            ['K.IQT-3-23', 'Iqtisodiyot va axborot texnologiyalari', 'rashidova.x@tisu.uz'],
            ['K.IQT-4-23', 'Iqtisodiyot va axborot texnologiyalari', 'nuriddinov.e@tisu.uz'],
            ['K.MMT-1-23.', 'Iqtisodiyot va axborot texnologiyalari', 'muzropova.s@tisu.uz'],
            ['K.MMT-2-23.', 'Iqtisodiyot va axborot texnologiyalari', 'madjitova.m@tisu.uz'],
            ['K.BX-1-23', 'Iqtisodiyot va axborot texnologiyalari', 'shodiev.a@tisu.uz'],
            ['K.BI-1-23', 'Iqtisodiyot va axborot texnologiyalari', 'xakimov.z@tisu.uz'],
            ['K.JIXIM-1-23', 'Iqtisodiyot va axborot texnologiyalari', 'eshqulova.n@tisu.uz'],
            ['K.ATT-1-23', 'Iqtisodiyot va axborot texnologiyalari', 'toxtaeva.n@tisu.uz'],
            ['K.ATT-2-23', 'Iqtisodiyot va axborot texnologiyalari', 'toraev.d@tisu.uz'],
            ['K.ATT-3-23', 'Iqtisodiyot va axborot texnologiyalari', 'ernazarov.m@tisu.uz'],
            ['K.T-1- 23', 'Iqtisodiyot va axborot texnologiyalari', 'torayev.z@tisu.uz'],
            ['K.IQT-122', 'Iqtisodiyot va axborot texnologiyalari', 'pardayev.l@tisu.uz'],
            ['K.IQT-222', 'Iqtisodiyot va axborot texnologiyalari', 'mamadjanova.t@tisu.uz'],
            ['MMT-122', 'Iqtisodiyot va axborot texnologiyalari', 'ismatov.s@tisu.uz'],
            ['K.BX-122', 'Iqtisodiyot va axborot texnologiyalari', 'shodiev.a@tisu.uz'],
            ['K.BI-122', 'Iqtisodiyot va axborot texnologiyalari', 'ziyodullayev.s@tisu.uz'],
            ['K.JIXIM-122', 'Iqtisodiyot va axborot texnologiyalari', 'pardayev.l@tisu.uz'],
            ['K.ATT-122', 'Iqtisodiyot va axborot texnologiyalari', 'begaliyev.a@tisu.uz'],
            ['K.BT-1-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'salohiddinova.n@tisu.uz'],
            ['K.BT -2-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'tojiyev.h@tisu.uz'],
            ['K.BT-3-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'toshpulatova.n@tisu.uz'],
            ['K.BT-4-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'djumayeva.d@tisu.uz'],
            ['K.BT-5-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'saidmurodov.a@tisu.uz'],
            ['K.BT–6-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'bakirov.j@tisu.uz'],
            ['K.BT–7-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'roziyeva.m@tisu.uz'],
            ['K.BT–8-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jumayev.i@tisu.uz'],
            ['K.BT–9-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'turayeva.g@tisu.uz'],
            ['K.BT–10-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'saidmurodov.a@tisu.uz'],
            ['K.BT–11-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'badalov.d@tisu.uz'],
            ['K.BT–12-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'zokirov.j@tisu.uz'],
            ['K.XT-1-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'ibodullayeva.d@tisu.uz'],
            ['K.XT-2-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'norqobilova.r@tisu.uz'],
            ['K.XT-3-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'kayumova.s@tisu.uz'],
            ['K.XT-4-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'erdanova.m@tisu.uz'],
            ['K.XT-5-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'yadigarova.s@tisu.uz'],
            ['K.XT-6-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'ochilova.a@tisu.uz'],
            ['K.XT-7-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'omonova.n@tisu.uz'],
            ['K.XT-8-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'oltiboyeva.k@tisu.uz'],
            ['K.XT-9-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'toshova.s@tisu.uz'],
            ['K.XT-10-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qosimov.b@tisu.uz'],
            ['K.XT-11-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'pardayev.a2@tisu.uz'],
            ['K.T-1-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'toshov.k@tisu.uz'],
            ['K.T-2-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'tursunov.a@tisu.uz'],
            ['K.T-3-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'abdunabiyev.h@tisu.uz'],
            ['K.T-4-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'tursunov.u@tisu.uz'],
            ['K.T.-5-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mamarajabov.g@tisu.uz'],
            ['K.T-6-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'abduraxmonov.a@tisu.uz'],
            ['K.T-7-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'karimov.a@tisu.uz'],
            ['K.T-8-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'raimov.l@tisu.uz'],
            ['K.T-9-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qosimov.a@tisu.uz'],
            ['K.T-10-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'raupova.n@tisu.uz'],
            ['F.O\'.T -1-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mukumova.d@tisu.uz'],
            ['F.O\'.T -2-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'rahmonov.b@tisu.uz'],
            ['F.O\'.T -3-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jorayeva.g@tisu.uz'],
            ['F.O\'.T -4-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xayrullayeva.l@tisu.uz'],
            ['F.O\'.T -5-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xabibullayeva.s@tisu.uz'],
            ['F.O\'.T -6-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'bakirov.j@tisu.uz'],
            ['F.O\'.T -7-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qoraqulov.a@tisu.uz'],
            ['F.O\'.T -8-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qurbonova.s@tisu.uz'],
            ['F.O\'.T -9-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'tangirov.r@tisu.uz'],
            ['F.O\'.T -10-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'chorshanbiyev.a@tisu.uz'],
            ['F.O\'.T -11-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'ismoilova.s@tisu.uz'],
            ['F.O\'.T -12-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'rahmonqulova.f@tisu.uz'],
            ['F.O\'.T -13-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'muxammadiyeva.d@tisu.uz'],
            ['F.O\'.T-14-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xayitmurodova.g@tisu.uz'],
            ['F.O\'.T -15-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xaitov.a@tisu.uz'],
            ['F.O\'.T -16-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'badalov.k@tisu.uz'],
            ['F.O\'.T -17-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'misirova.n@tisu.uz'],
            ['F.O\'.T -18-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mingtorayeva.u@tisu.uz'],
            ['F.O\'.T -19-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jumayev.i@tisu.uz'],
            ['F.O\'.T -20-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'chorshanbiyev.a@tisu.uz'],
            ['F.I.T -1-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mengboyev.a@tisu.uz'],
            ['F.I.T -2-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'narmuratov.z@tisu.uz'],
            ['F.I.T -3-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'choriyev.u@tisu.uz'],
            ['F.I.T -4-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mingnarova.m@tisu.uz'],
            ['F.I.T -5-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'shodiyeva.n@tisu.uz'],
            ['F.I.T-6-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xurramova.d@tisu.uz'],
            ['F.I.T-7-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'shonazarova.g@tisu.uz'],
            ['F.I.T-8-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xaydarova.m@tisu.uz'],
            ['F.I.T 9-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'abdunazarov.o@tisu.uz'],
            ['F.I.T 10-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'toshboyeva.u@tisu.uz'],
            ['F.I.T 11-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mengliqulova.m@tisu.uz'],
            ['F.I.T 12-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'azizjonova.a@tisu.uz'],
            ['F.I.T 13-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qosimov.b@tisu.uz'],
            ['F.I.T 14-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'masadikova.x@tisu.uz'],
            ['F.I.T 15-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'rahimova.s@tisu.uz'],
            ['F.I.T 16-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'norqobilova.n@tisu.uz'],
            ['F.R.T 1-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qurbonova.n@tisu.uz'],
            ['F.R.T 2-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xonova.d@tisu.uz'],
            ['F.R.T 3-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'hudoyorova.g@tisu.uz'],
            ['F.R.T 4-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'kamalov.u@tisu.uz'],
            ['F.R.T 5-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mahmadiyeva.g@tisu.uz'],
            ['KP 1-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'alimardanova.r@tisu.uz'],
            ['KP 2-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jorayev.a@tisu.uz'],
            ['KP 3-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'avliyaqulov.t@tisu.uz'],
            ['K.M.T 1-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'almardanov.j@tisu.uz'],
            ['K.MT-2-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xojamqulova.i@tisu.uz'],
            ['K.MT-3-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qarshiyeva.i@tisu.uz'],
            ['K.TT-1-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'eshqorayev.u@tisu.uz'],
            ['K.JM-1-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'bekmirzayev.s@tisu.uz'],
            ['K.JM-2-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'bekmirzayev.s@tisu.uz'],
            ['K.JM-3-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'ibragimov.a@tisu.uz'],
            ['K.JM-4-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'usmonov.m@tisu.uz'],
            ['K.JM-5-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'usmonov.m@tisu.uz'],
            ['K.JM-6-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'ibragimov.a@tisu.uz'],
            ['K.JM-7-25', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'babayev.a@tisu.uz'],
            ['K.BT-1-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'salomov.g@tisu.uz'],
            ['K.BT-2-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'pardayev.a2@tisu.uz'],
            ['K.BT-3-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'hayitova.f@tisu.uz'],
            ['K.BT-4-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'bazarov.s@tisu.uz'],
            ['K.BT-5-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'abdinabiyev.x@tisu.uz'],
            ['K.BT-6-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'yuldashev.e@tisu.uz'],
            ['K.XT-1-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'shoyimova.k@tisu.uz'],
            ['K.XT-2-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mingboyev.o@tisu.uz'],
            ['K.XT-3-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'boriyeva.m@tisu.uz'],
            ['K.XT-4-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'toshpolatov.a@tisu.uz'],
            ['K.XT-5-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'boriyeva.s@tisu.uz'],
            ['K.XT-6-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qurbonova.s@tisu.uz'],
            ['K.XT-7-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'boriyev.s@tisu.uz'],
            ['K.XT-8-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'ochilova.a@tisu.uz'],
            ['K.XT-9-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qalandarov.q@tisu.uz'],
            ['K.XT-10-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mengnarov.a@tisu.uz'],
            ['K.T-1-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'nazarov.o@tisu.uz'],
            ['K.T-2-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'abdurahmonov.a@tisu.uz'],
            ['K.T-3-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'fayzullayeva.m@tisu.uz'],
            ['F.O\'.T-1-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'boysoatov.m@tisu.uz'],
            ['F.O\'.T-2-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'ahmedov.e@tisu.uz'],
            ['F.O\'.T-3-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'norqulova.s@tisu.uz'],
            ['F.O\'.T-4-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xolmurotova.s@tisu.uz'],
            ['F.O\'.T-5-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'aminova.d@tisu.uz'],
            ['F.O\'.T-6-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'abduraxmonov.a@tisu.uz'],
            ['F.O\'.T-7-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'tangirov.r@tisu.uz'],
            ['F.O\'.T-8-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mingnarova.m@tisu.uz'],
            ['F.O\'.T-9-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jumayeva.s@tisu.uz'],
            ['F.O\'.T-10-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jumayeva.s@tisu.uz'],
            ['F.I.T-1-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'nematullayev.n@tisu.uz'],
            ['F.I.T-2-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'allayarova.s@tisu.uz'],
            ['F.I.T-3-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'oralova.o@tisu.uz'],
            ['F.I.T-4-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'saydullayev.f@tisu.uz'],
            ['F.I.T-5-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'berdimurodova.s@tisu.uz'],
            ['F.I.T-6-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'sohibova.d@tisu.uz'],
            ['F.I.T-7-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qodirova.s@tisu.uz'],
            ['F.I.T-8-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'rozimurodova.s@tisu.uz'],
            ['F.I.T-9-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'nuriddinov.e@tisu.uz'],
            ['K.F.R.T-1-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'hudoyorova.g@tisu.uz'],
            ['K.F.R.T-2-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jabborova.n@tisu.uz'],
            ['K.F.R.T-3-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jumayev.o@tisu.uz'],
            ['K.F.R.T-4-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'sattarova.y@tisu.uz'],
            ['K.P-1-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'norbosheva.m@tisu.uz'],
            ['K.JM-1-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'boboqulov.c@tisu.uz'],
            ['K.JM-2-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'begimkulov.o@tisu.uz'],
            ['K.MT-1-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'toshova.s@tisu.uz'],
            ['K.MT-2-24', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mengturayeva.u@tisu.uz'],
            ['K.BT-1-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'badalov.d@tisu.uz'],
            ['K.BT-2-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'tojiyev.h@tisu.uz'],
            ['K.BT-3-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'zokirov.j@tisu.uz'],
            ['K.BT-4-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'abdusamatov.a@tisu.uz'],
            ['K.BT-5-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'eshboyeva.s@tisu.uz'],
            ['K.BT-6-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'yuldashev.e@tisu.uz'],
            ['K.BT-7-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'babayeva.m@tisu.uz'],
            ['K.XT-1-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'davlyatova.m@tisu.uz'],
            ['K.XT-2-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mukumova.d@tisu.uz'],
            ['K.XT-3-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mengboyev.a@tisu.uz'],
            ['K.XT-4-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jabborov.f@tisu.uz'],
            ['K.XT-5-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mustafaqulova.z@tisu.uz'],
            ['K.XT-6-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'djumayeva.d@tisu.uz'],
            ['K.T-1-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'yormatova.f@tisu.uz'],
            ['K.T-2-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'eshqurbonov.s@tisu.uz'],
            ['K.T-3-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qobilov.k@tisu.uz'],
            ['F.O\'.T-1-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'bobomurodova.s@tisu.uz'],
            ['F.O\'.T-2-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'almardonova.i@tisu.uz'],
            ['F.O\'.T-3-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qoraqulov.a@tisu.uz'],
            ['F.O\'.T-4-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'ergasheva.r@tisu.uz'],
            ['F.O\'.T-5-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'habibullayeva.s@tisu.uz'],
            ['F.O\'.T-6-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'boriyev.s@tisu.uz'],
            ['F.O\'.T-7-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mengnarov.a2@tisu.uz'],
            ['F.I.T-1-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jabbarova.s@tisu.uz'],
            ['F.I.T-2-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'ismoilov.b@tisu.uz'],
            ['F.I.T-3-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'shonazarova.s@tisu.uz'],
            ['F.I.T-4-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xurramova.m@tisu.uz'],
            ['K.F.R.T-1-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'mahmadiyeva.g@tisu.uz'],
            ['K.F.R.T-2-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xonova.d@tisu.uz'],
            ['K.F.R.T-3-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jabborova.n@tisu.uz'],
            ['K.F.R.T-4-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jumayev.o@tisu.uz'],
            ['K.F.R.T-5-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qurbonova.n@tisu.uz'],
            ['K.MBXT-1-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'karimov.a@tisu.uz'],
            ['K.MBXT-2-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xayrullayeva.l@tisu.uz'],
            ['K.MBXT-3-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xamrayeva.r@tisu.uz'],
            ['K.P.P-1-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xolov.o@tisu.uz'],
            ['K.P.P-2-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jumayeva.g@tisu.uz'],
            ['K.M.T-1-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'almardanov.j2@tisu.uz'],
            ['K.M.T-2-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'qarshiyeva.i2@tisu.uz'],
            ['K.J.M-1-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'babayev.a@tisu.uz'],
            ['K.J.M-2-23', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'salimov.o@tisu.uz'],
            ['K.BT-122', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'jorayev.a2@tisu.uz'],
            ['K.BT-222', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'badalov.k2@tisu.uz'],
            ['K.BT-322', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'amirqulova.z@tisu.uz'],
            ['K.XT-122', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'abdinazarov.o@tisu.uz'],
            ['K.XT-222', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'raimov.l@tisu.uz'],
            ['K.XT-322', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'salomova.g@tisu.uz'],
            ['K.T.T-122', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'tursunov.n@tisu.uz'],
            ['K.O\'.T-122', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'bazarov.s@tisu.uz'],
            ['K.O\'.T-222', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'karimov.a2@tisu.uz'],
            ['K.I.T-122', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'allayev.z@tisu.uz'],
            ['K.I.T-222', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'madiyeva.m@tisu.uz'],
            ['K.F.R.T-122', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'suleymanov.d@tisu.uz'],
            ['K.F.R.T-222', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'kamalov.u@tisu.uz'],
            ['K.P.P-122', 'Pedagogika va ijtimoiy-gumanitar fanlar', 'xaitov.a2@tisu.uz'],
            ['D-25-01', 'Tibbiyot', 'rasulov.a@tisu.uz'],
            ['D-25-02', 'Tibbiyot', 'buzrukov.t@tisu.uz'],
            ['D-25-03', 'Tibbiyot', 'umirqulova.f@tisu.uz'],
            ['D-25-04', 'Tibbiyot', 'roziyeva.g@tisu.uz'],
            ['D-25-05', 'Tibbiyot', 'babamuratov.b@tisu.uz'],
            ['D-25-06', 'Tibbiyot', 'yarov.u@tisu.uz'],
            ['D-25-07', 'Tibbiyot', 'tillyayeva.z@tisu.uz'],
            ['D-25-08', 'Tibbiyot', 'tashpolatov.t@tisu.uz'],
            ['D-25-09', 'Tibbiyot', 'torauev.x@tisu.uz'],
            ['D-25-10', 'Tibbiyot', 'annayev.u@tisu.uz'],
            ['D-25-11', 'Tibbiyot', 'rasulov.a@tisu.uz'],
            ['D-25-12', 'Tibbiyot', 'togayev.a@tisu.uz'],
            ['D-25-13', 'Tibbiyot', 'torauev.x@tisu.uz'],
            ['D-25-14', 'Tibbiyot', 'roziyeva.g@tisu.uz'],
            ['D-25-15', 'Tibbiyot', 'roziyeva.g@tisu.uz'],
            ['D-25-16', 'Tibbiyot', 'annayev.u@tisu.uz'],
            ['D-25-17', 'Tibbiyot', 'meyliyev.z@tisu.uz'],
            ['D-25-18', 'Tibbiyot', 'saidov.j@tisu.uz'],
            ['D-25-19', 'Tibbiyot', 'nurislomova.l@tisu.uz'],
            ['D-25-20', 'Tibbiyot', 'annayev.u@tisu.uz'],
            ['D-25-21', 'Tibbiyot', 'soatova.z@tisu.uz'],
            ['D-25-22', 'Tibbiyot', 'buzrukov.t@tisu.uz'],
            ['D-25-23', 'Tibbiyot', 'umirqulova.f@tisu.uz'],
            ['D-25-24', 'Tibbiyot', 'qayumova.s@tisu.uz'],
            ['D-25-25', 'Tibbiyot', 'babamuratov.b@tisu.uz'],
            ['D-25-26', 'Tibbiyot', 'torauev.x@tisu.uz'],
            ['D-25-27', 'Tibbiyot', 'kochkeldiyeva.s@tisu.uz'],
            ['D-25-28', 'Tibbiyot', 'shonazarova.g@tisu.uz'],
            ['D-25-29', 'Tibbiyot', 'boyqobilov.s@tisu.uz'],
            ['D-25-30', 'Tibbiyot', 'chariyev.m@tisu.uz'],
            ['D-25-31', 'Tibbiyot', 'boyqulov.t@tisu.uz'],
            ['D-25-32', 'Tibbiyot', 'kibriyeva.m@tisu.uz'],
            ['D-25-33', 'Tibbiyot', 'umirqulova.f@tisu.uz'],
            ['D-25-34', 'Tibbiyot', 'meyliyev.z@tisu.uz'],
            ['D-25-35', 'Tibbiyot', 'jorayev.s@tisu.uz'],
            ['D-25-36', 'Tibbiyot', 'kocharova.m@tisu.uz'],
            ['D-25-37', 'Tibbiyot', 'boyqobilov.s@tisu.uz'],
            ['D-25-38', 'Tibbiyot', 'kocharova.m@tisu.uz'],
            ['D-25-39', 'Tibbiyot', 'qurbonova.g@tisu.uz'],
            ['D-25-40', 'Tibbiyot', 'hazratqulova.o@tisu.uz'],
            ['S-25-01', 'Tibbiyot', 'torauev.x@tisu.uz'],
            ['S-25-02', 'Tibbiyot', 'boyqobilov.s@tisu.uz'],
            ['S-25-03', 'Tibbiyot', 'kibriyeva.m@tisu.uz'],
            ['S-25-04', 'Tibbiyot', 'buzrukov.t@tisu.uz'],
            ['S-25-05', 'Tibbiyot', 'meyliyev.z@tisu.uz'],
            ['S-25-06', 'Tibbiyot', 'xamrayev.r@tisu.uz'],
            ['S-25-07', 'Tibbiyot', 'tojimurodov@tisu.uz'],
            ['S-25-08', 'Tibbiyot', 'jorayev.s@tisu.uz'],
            ['S-25-09', 'Tibbiyot', 'tashpolatov.t@tisu.uz'],
            ['S-25-10', 'Tibbiyot', 'boyqulov.t@tisu.uz'],
            ['S-25-11', 'Tibbiyot', 'jorayev.z@tisu.uz'],
            ['S-25-12', 'Tibbiyot', 'xamrayev.r@tisu.uz'],
            ['S-25-13', 'Tibbiyot', 'qurbonova.g@tisu.uz'],
            ['S-25-14', 'Tibbiyot', 'sultonov.r@tisu.uz'],
            ['S-25-15', 'Tibbiyot', 'tojimurodov@tisu.uz'],
            ['B-25-01', 'Tibbiyot', 'sultonov.s@tisu.uz'],
            ['B-25-02', 'Tibbiyot', 'slanova.x@tisu.uz'],
            ['B-25-03', 'Tibbiyot', 'sultonov.s@tisu.uz'],
            ['B-25-04', 'Tibbiyot', 'slanova.x@tisu.uz'],
            ['B-25-05', 'Tibbiyot', 'nurislomova.l@tisu.uz'],
            ['B-25-06', 'Tibbiyot', 'nurislomova.l@tisu.uz'],
            ['B-25-07', 'Tibbiyot', 'raimov.s@tisu.uz'],
            ['B-25-08', 'Tibbiyot', 'hazratqulova.o@tisu.uz'],
            ['P-25-01', 'Tibbiyot', 'togayev.a@tisu.uz'],
            ['P-25-02', 'Tibbiyot', 'togayev.a@tisu.uz'],
            ['P-25-03', 'Tibbiyot', 'sultonov.r@tisu.uz'],
            ['F-25-01', 'Tibbiyot', 'jorayev.z@tisu.uz'],
            ['F-25-02', 'Tibbiyot', 'hazratqulova.o@tisu.uz'],
            ['D-24-01', 'Tibbiyot', 'sultonov.r@tisu.uz'],
            ['D-24-02', 'Tibbiyot', 'xolmurodov.i@tisu.uz'],
            ['D-24-03', 'Tibbiyot', 'saidov.j@tisu.uz'],
            ['D-24-04', 'Tibbiyot', 'axmedov.u@tisu.uz'],
            ['D-24-05', 'Tibbiyot', 'babamurodov.a@tisu.uz'],
            ['D-24-06', 'Tibbiyot', 'xolmurodov.i@tisu.uz'],
            ['D-24-07', 'Tibbiyot', 'meyliyev.z@tisu.uz'],
            ['D-24-08', 'Tibbiyot', 'saidov.j@tisu.uz'],
            ['D-24-09', 'Tibbiyot', 'eshqobilov.o@tisu.uz'],
            ['D-24-10', 'Tibbiyot', 'enjayev.y@tisu.uz'],
            ['D-24-11', 'Tibbiyot', 'xudoyqulova.z@tisu.uz'],
            ['D-24-12', 'Tibbiyot', 'xudoyqulova.z@tisu.uz'],
            ['D-24-13', 'Tibbiyot', 'tursunov.q@tisu.uz'],
            ['D-24-14', 'Tibbiyot', 'bekmirzayev.e@tisu.uz'],
            ['D-24-15', 'Tibbiyot', 'axmedov.u@tisu.uz'],
            ['D-24-16', 'Tibbiyot', 'babamurodov.a@tisu.uz'],
            ['D-24-17', 'Tibbiyot', 'axmedov.u@tisu.uz'],
            ['D-24-18', 'Tibbiyot', 'saidov.j@tisu.uz'],
            ['D-24-19', 'Tibbiyot', 'ziyodullayeva.l@tisu.uz'],
            ['D-24-20', 'Tibbiyot', 'eshqobilov.o@tisu.uz'],
            ['D-24-21', 'Tibbiyot', 'enjayev.y@tisu.uz'],
            ['D-24-22', 'Tibbiyot', 'boriyev.m@tisu.uz'],
            ['D-24-23', 'Tibbiyot', 'hazratqulova.o@tisu.uz'],
            ['D-24-24', 'Tibbiyot', 'alimova.z@tisu.uz'],
            ['D-24-25', 'Tibbiyot', 'enjayev.y@tisu.uz'],
            ['D-24-26', 'Tibbiyot', 'polatov.m@tisu.uz'],
            ['S-24-01', 'Tibbiyot', 'qayumova.s@tisu.uz'],
            ['S-24-02', 'Tibbiyot', 'tursunov.q@tisu.uz'],
            ['S-24-03', 'Tibbiyot', 'jorayev.s@tisu.uz'],
            ['S-24-04', 'Tibbiyot', 'qayumova.s@tisu.uz'],
            ['S-24-05', 'Tibbiyot', 'tillyayeva.z@tisu.uz'],
            ['S-24-06', 'Tibbiyot', 'xolmurodov.i@tisu.uz'],
            ['S-24-07', 'Tibbiyot', 'jorayev.s@tisu.uz'],
            ['S-24-08', 'Tibbiyot', 'ergashev.n@tisu.uz'],
            ['S-24-09', 'Tibbiyot', 'xolmurodov.i@tisu.uz'],
            ['B-24-01', 'Tibbiyot', 'slanova.x@tisu.uz'],
            ['P-24-01', 'Tibbiyot', 'mamadiyeva.z@tisu.uz'],
            ['P-24-02', 'Tibbiyot', 'boriyev.m@tisu.uz'],
            ['F-24-01', 'Tibbiyot', 'jorayev.z@tisu.uz'],
            ['D-23-01', 'Tibbiyot', 'xalbayeva.z@tisu.uz'],
            ['D-23-02', 'Tibbiyot', 'shermatov.x@tisu.uz'],
            ['D-23-03', 'Tibbiyot', 'saidov.j@tisu.uz'],
            ['D-23-04', 'Tibbiyot', 'chorshanbiyev.c@tisu.uz'],
            ['D-23-05', 'Tibbiyot', 'polatov.m@tisu.uz'],
            ['D-23-06', 'Tibbiyot', 'xaitov.a3@tisu.uz'],
            ['D-23-07', 'Tibbiyot', 'saidov.x@tisu.uz'],
            ['D-23-08', 'Tibbiyot', 'husanov.s@tisu.uz'],
            ['D-23-09', 'Tibbiyot', 'boriyeva.d@tisu.uz'],
            ['D-23-10', 'Tibbiyot', 'ibragimova.g@tisu.uz'],
            ['D-23-11', 'Tibbiyot', 'kibriyev.b@tisu.uz'],
            ['D-23-12', 'Tibbiyot', 'aminqulov.s@tisu.uz'],
            ['D-23-13', 'Tibbiyot', 'husanov.s@tisu.uz'],
            ['D-23-14', 'Tibbiyot', 'alimova.z@tisu.uz'],
            ['D-23-15', 'Tibbiyot', 'shermatov.x@tisu.uz'],
            ['D-23-16', 'Tibbiyot', 'abdusamiyeva.n@tisu.uz'],
            ['D-23-17', 'Tibbiyot', 'choriyev.a@tisu.uz'],
            ['D-23-18', 'Tibbiyot', 'abdusamiyeva.n@tisu.uz'],
            ['S-23-01', 'Tibbiyot', 'hayitova.m@tisu.uz'],
            ['S-23-02', 'Tibbiyot', 'hayitova.m@tisu.uz'],
            ['S-23-03', 'Tibbiyot', 'pardayev.o@tisu.uz'],
            ['S-23-04', 'Tibbiyot', 'oqboyev.z@tisu.uz'],
            ['S-23-05', 'Tibbiyot', 'xaitov.a3@tisu.uz'],
            ['S-23-06', 'Tibbiyot', 'hayitova.m@tisu.uz'],
            ['D-22-01', 'Tibbiyot', 'boriyeva.d@tisu.uz'],
            ['D-22-02', 'Tibbiyot', 'chariyev.m@tisu.uz'],
            ['D-22-03', 'Tibbiyot', 'roziyev.o@tisu.uz'],
            ['D-22-04', 'Tibbiyot', 'choriyev.a@tisu.uz'],
            ['D-22-05', 'Tibbiyot', 'roziyev.o@tisu.uz'],
            ['D-22-06', 'Tibbiyot', 'kibriyev.b@tisu.uz'],
            ['D-22-07', 'Tibbiyot', 'boriyeva.d@tisu.uz'],
            ['D-22-08', 'Tibbiyot', 'xolboyev.n@tisu.uz'],
            ['D-22-09', 'Tibbiyot', 'alimova.z@tisu.uz'],
            ['S-22-01', 'Tibbiyot', 'pardayev.o@tisu.uz'],
            ['S-22-02', 'Tibbiyot', 'saidov.j@tisu.uz'],
            ['S-22-03', 'Tibbiyot', 'hayitova.m@tisu.uz'],
            ['S-22-04', 'Tibbiyot', 'xolboyev.n@tisu.uz'],
            ['S-22-05', 'Tibbiyot', 'oqboyev.z@tisu.uz'],
            ['S-22-06', 'Tibbiyot', 'aminqulov.s@tisu.uz'],
        ];

        foreach ($groups as [$name, $facultyName, $curatorEmail]) {
            Group::create([
                'name' => $name,
                'faculty_id' => $faculties[$facultyName],
                'curator_id' => $curators[$curatorEmail],
                'is_active' => true,
            ]);
        }
    }
}
